In [2]:
with open('C:\\Users\\RITESH TIWARI\\Desktop\\fdf/brent.txt','r')as f:
    brent = f.read().splitlines()
with open('C:\\Users\\RITESH TIWARI\\Desktop\\fdf/camden.txt','r')as c:
    camden = c.read().splitlines()    
with open('C:\\Users\\RITESH TIWARI\\Desktop\\fdf/redbridge.txt','r')as r:
    redbridge = r.read().splitlines() 
with open('C:\\Users\\RITESH TIWARI\\Desktop\\fdf/southwark.txt','r')as s:
    southwark = s.read().splitlines() 
    
    



In [3]:
print(brent)
print(camden)
print(redbridge)
print(southwark)

['Brent Park', 'Church End', 'Dollis Hill', 'Harlesden', 'Kensal Green', 'Kingsbury', 'Neasden', 'Preston', "Queen's Park", 'Tokyngton', 'Wembley', 'Wembley Park', 'Willesden', 'Park Royal', 'Kenton', 'Kilburn', 'Sudbury', 'Brondesbury', 'Alperton']
['Chalk Farm', 'Dartmouth Park', 'Fitzrovia', 'Frognal', 'Bloomsbury', 'Gospel Oak', 'Hampstead', 'Highgate', 'Holborn', 'Kentish Town', 'Gospel Oak', 'Primrose Hill', 'Somerstown', 'St Giles', 'St Pancras', 'Swiss Cottage', 'West Hampstead', "King's Cross", 'Somerstown', 'Belsize Park', 'Bloomsbury', 'Camden Town']
['Chadwell Heath', 'Gants Hill', 'Goodmayes', 'Snaresbrook', 'Hainault', 'Ilford', 'Loxford', 'Newbury Park', 'Hainault', 'Redbridge', 'Seven Kings', 'South Woodford', 'Wanstead', 'Woodford', 'Woodford Green', 'Snaresbrook', 'Aldborough Hatch', 'Barkingside']
['Denmark Hill', 'Dulwich', 'Surrey Quays', 'East Dulwich', 'Elephant and Castle', 'Newington', 'Nunhead', 'Peckham', 'Rotherhithe', 'Surrey Quays', 'Nunhead', 'Walworth', 

In [3]:
print(brent[0:4])
print(camden[0:4])
print(redbridge[0:4])
print(southwark[0:4])


['Brent Park', 'Church End', 'Dollis Hill', 'Harlesden']
['Chalk Farm', 'Dartmouth Park', 'Fitzrovia', 'Frognal']
['Chadwell Heath', 'Gants Hill', 'Goodmayes', 'Snaresbrook']
['Denmark Hill', 'Dulwich', 'Surrey Quays', 'East Dulwich']


In [4]:
print(len(brent))
print(len(camden))
print(len(redbridge))
print(len(southwark))

19
22
18
15


In [5]:
if 'Newbury Park'in redbridge:
    print('yes available')
else:
    print('not available')

yes available


In [6]:
if 'Peckham'in brent:
    print('yes available')
else:
    print('not available')

not available


In [7]:
print(f'maximum value in brent list is:{max(brent)} \n minimun valuein brent list is :{min(brent)}')
print(f'maximum value in camden list is:{max(camden)} \n minimun value in camden list is :{min(camden)}')
print(f'maximum value in redbridge list is:{max(redbridge)} \n minimun value in redbridge list is :{min(redbridge)}')
print(f'maximum value in southwark list is:{max(southwark)} \n minimun value in southwark list is :{min(southwark)}')

maximum value in brent list is:Willesden 
 minimun valuein brent list is :Alperton
maximum value in camden list is:West Hampstead 
 minimun value in camden list is :Belsize Park
maximum value in redbridge list is:Woodford Green 
 minimun value in redbridge list is :Aldborough Hatch
maximum value in southwark list is:Walworth 
 minimun value in southwark list is :Bankside


In [8]:
with open('C:\\Users\\RITESH TIWARI\\Desktop\\fdf/brent.txt','r')as f:
    brent = f.read().splitlines()
print(brent)    

['Brent Park', 'Church End', 'Dollis Hill', 'Harlesden', 'Kensal Green', 'Kingsbury', 'Neasden', 'Preston', "Queen's Park", 'Tokyngton', 'Wembley', 'Wembley Park', 'Willesden', 'Park Royal', 'Kenton', 'Kilburn', 'Sudbury', 'Brondesbury', 'Alperton']


In [9]:
aifa=[]
for i in brent:
    if i==i:
        aifa+=i
print(aifa)
    

['B', 'r', 'e', 'n', 't', ' ', 'P', 'a', 'r', 'k', 'C', 'h', 'u', 'r', 'c', 'h', ' ', 'E', 'n', 'd', 'D', 'o', 'l', 'l', 'i', 's', ' ', 'H', 'i', 'l', 'l', 'H', 'a', 'r', 'l', 'e', 's', 'd', 'e', 'n', 'K', 'e', 'n', 's', 'a', 'l', ' ', 'G', 'r', 'e', 'e', 'n', 'K', 'i', 'n', 'g', 's', 'b', 'u', 'r', 'y', 'N', 'e', 'a', 's', 'd', 'e', 'n', 'P', 'r', 'e', 's', 't', 'o', 'n', 'Q', 'u', 'e', 'e', 'n', "'", 's', ' ', 'P', 'a', 'r', 'k', 'T', 'o', 'k', 'y', 'n', 'g', 't', 'o', 'n', 'W', 'e', 'm', 'b', 'l', 'e', 'y', 'W', 'e', 'm', 'b', 'l', 'e', 'y', ' ', 'P', 'a', 'r', 'k', 'W', 'i', 'l', 'l', 'e', 's', 'd', 'e', 'n', 'P', 'a', 'r', 'k', ' ', 'R', 'o', 'y', 'a', 'l', 'K', 'e', 'n', 't', 'o', 'n', 'K', 'i', 'l', 'b', 'u', 'r', 'n', 'S', 'u', 'd', 'b', 'u', 'r', 'y', 'B', 'r', 'o', 'n', 'd', 'e', 's', 'b', 'u', 'r', 'y', 'A', 'l', 'p', 'e', 'r', 't', 'o', 'n']


In [10]:
with open('C:\\Users\\RITESH TIWARI\\Desktop\\fdf/brent.txt','r')as f:
    brent = f.read().splitlines()
print(brent)   


def duplicate(camden):
    lis2=[]
    dups=[]
    count =0
    for name in camden:
        if name not in lis2:
            lis2.append(name)
        elif name in lis2:
            dups.append(name)
    dups_count = {i:dups.count(i) for i in dups}
    
    if len(dups)==0:
        return ("For the given list no duplicates found")
    else:
        return ("Please find the list of duplicates along with their counts:",dups_count)
print(duplicate(brent))
    

['Brent Park', 'Church End', 'Dollis Hill', 'Harlesden', 'Kensal Green', 'Kingsbury', 'Neasden', 'Preston', "Queen's Park", 'Tokyngton', 'Wembley', 'Wembley Park', 'Willesden', 'Park Royal', 'Kenton', 'Kilburn', 'Sudbury', 'Brondesbury', 'Alperton']
For the given list no duplicates found


In [11]:
# Finding duplicates in all 3 regions

dup_camden    = []
dup_redbridge = []
dup_southwark = []

locs = [camden,redbridge,southwark]
for lo in locs:
        if lo==camden:
            for c in lo:
                if (lo.count(c))>1:
                    vali = c in dup_camden
                    if vali== False :
                        dup_camden.append(c)                        
               
        if lo==redbridge:
            for c in lo:
                if (lo.count(c))>1:
                    vali = c in dup_redbridge
                    if vali== False :
                        dup_redbridge.append(c)
                        

        if lo == southwark:
            for c in lo:
                if (lo.count(c))>1:
                    vali = c in dup_southwark
                    if vali== False :
                        dup_southwark.append(c) 
                        
# to print all duplicate locations            
duplis = {'camden':dup_camden,'rb' : dup_redbridge,'sw' :dup_southwark}
for key, value


SyntaxError: invalid syntax (<ipython-input-11-c4b0a8f1b1b1>, line 33)

In [ ]:
print(brent)

In [ ]:
print(duplicate(brent))

In [23]:
#math=100,science=100,history=100,geogrophy=100
math=int(input('please enter your math marks' ))
science=int(input('please enter your science marks' ))
history=int(input('please enter your history marks' ))
geography=int(input('please enter your geography marks' ))
sum1=(math+science+history+geography)
print(sum1)

if 0<sum1<100:
    print('fail')
elif 100<sum1<250:
    print('good')
else:
    print('a')
    

please enter your math marks100
please enter your science marks100
please enter your history marks100
please enter your geography marks100
400
a


In [4]:
with open('C:\\Users\\RITESH TIWARI\\Desktop\\fdf/brent.txt','r')as f:
    brent = f.read().splitlines()
with open('C:\\Users\\RITESH TIWARI\\Desktop\\fdf/camden.txt','r')as c:
    camden = c.read().splitlines()    
with open('C:\\Users\\RITESH TIWARI\\Desktop\\fdf/redbridge.txt','r')as r:
    redbridge = r.read().splitlines() 
with open('C:\\Users\\RITESH TIWARI\\Desktop\\fdf/southwark.txt','r')as s:
    southwark = s.read().splitlines()   

['Brent Park', 'Church End', 'Dollis Hill', 'Harlesden', 'Kensal Green', 'Kingsbury', 'Neasden', 'Preston', "Queen's Park", 'Tokyngton', 'Wembley', 'Wembley Park', 'Willesden', 'Park Royal', 'Kenton', 'Kilburn', 'Sudbury', 'Brondesbury', 'Alperton']


In [5]:
print(brent)

['Brent Park', 'Church End', 'Dollis Hill', 'Harlesden', 'Kensal Green', 'Kingsbury', 'Neasden', 'Preston', "Queen's Park", 'Tokyngton', 'Wembley', 'Wembley Park', 'Willesden', 'Park Royal', 'Kenton', 'Kilburn', 'Sudbury', 'Brondesbury', 'Alperton']


In [4]:
print(len(brent))
print(len(camden))
print(len(redbridge))
print(len(southwark))

19
22
18
15


In [6]:
len (camden)== len(list(set(camden)))

False

In [6]:
print(camden)

['Chalk Farm', 'Dartmouth Park', 'Fitzrovia', 'Frognal', 'Bloomsbury', 'Gospel Oak', 'Hampstead', 'Highgate', 'Holborn', 'Kentish Town', 'Gospel Oak', 'Primrose Hill', 'Somerstown', 'St Giles', 'St Pancras', 'Swiss Cottage', 'West Hampstead', "King's Cross", 'Somerstown', 'Belsize Park', 'Bloomsbury', 'Camden Town']


In [31]:
#all=[brent,camden,redbridge,southwark]

orignal=[]
for i in camden:
    if i not in orignal:
        orignal.append(i)
print(orignal)
print(len(orignal))

        

['Chalk Farm', 'Dartmouth Park', 'Fitzrovia', 'Frognal', 'Bloomsbury', 'Gospel Oak', 'Hampstead', 'Highgate', 'Holborn', 'Kentish Town', 'Primrose Hill', 'Somerstown', 'St Giles', 'St Pancras', 'Swiss Cottage', 'West Hampstead', "King's Cross", 'Belsize Park', 'Camden Town']
19


In [6]:
def sam(d):
    gaga=[]
    for i in d:
        if i not in gaga:
            gaga.append(i)
    return gaga      
ali=[brent,camden,redbridge,southwark]
for i in ali:
    print(sam(i))
    print(len(sam(i)))

['Brent Park', 'Church End', 'Dollis Hill', 'Harlesden', 'Kensal Green', 'Kingsbury', 'Neasden', 'Preston', "Queen's Park", 'Tokyngton', 'Wembley', 'Wembley Park', 'Willesden', 'Park Royal', 'Kenton', 'Kilburn', 'Sudbury', 'Brondesbury', 'Alperton']
19
['Chalk Farm', 'Dartmouth Park', 'Fitzrovia', 'Frognal', 'Bloomsbury', 'Gospel Oak', 'Hampstead', 'Highgate', 'Holborn', 'Kentish Town', 'Primrose Hill', 'Somerstown', 'St Giles', 'St Pancras', 'Swiss Cottage', 'West Hampstead', "King's Cross", 'Belsize Park', 'Camden Town']
19
['Chadwell Heath', 'Gants Hill', 'Goodmayes', 'Snaresbrook', 'Hainault', 'Ilford', 'Loxford', 'Newbury Park', 'Redbridge', 'Seven Kings', 'South Woodford', 'Wanstead', 'Woodford', 'Woodford Green', 'Aldborough Hatch', 'Barkingside']
16
['Denmark Hill', 'Dulwich', 'Surrey Quays', 'East Dulwich', 'Elephant and Castle', 'Newington', 'Nunhead', 'Peckham', 'Rotherhithe', 'Walworth', 'Bermondsey', 'Camberwell', 'Bankside']
13


### Dictionary function and loop

In [ ]:
# you need to add these below two into locations with the specified names

# Inner_london  = camden + southwark
# Outer_london  = brent + redbridge

# number of locations in all 6 regions need to print with help of loop

# by using conditional statment need to find from where i need to start my toure{more locs is my choice}

In [5]:
dic={'brent':brent,'camden':camden,'redbridge':redbridge,'southwark':southwark}
print(dic)
print('________________________________________________________________________________________________________________________')
print(dic.items())

{'brent': ['Brent Park', 'Church End', 'Dollis Hill', 'Harlesden', 'Kensal Green', 'Kingsbury', 'Neasden', 'Preston', "Queen's Park", 'Tokyngton', 'Wembley', 'Wembley Park', 'Willesden', 'Park Royal', 'Kenton', 'Kilburn', 'Sudbury', 'Brondesbury', 'Alperton'], 'camden': ['Chalk Farm', 'Dartmouth Park', 'Fitzrovia', 'Frognal', 'Bloomsbury', 'Gospel Oak', 'Hampstead', 'Highgate', 'Holborn', 'Kentish Town', 'Gospel Oak', 'Primrose Hill', 'Somerstown', 'St Giles', 'St Pancras', 'Swiss Cottage', 'West Hampstead', "King's Cross", 'Somerstown', 'Belsize Park', 'Bloomsbury', 'Camden Town'], 'redbridge': ['Chadwell Heath', 'Gants Hill', 'Goodmayes', 'Snaresbrook', 'Hainault', 'Ilford', 'Loxford', 'Newbury Park', 'Hainault', 'Redbridge', 'Seven Kings', 'South Woodford', 'Wanstead', 'Woodford', 'Woodford Green', 'Snaresbrook', 'Aldborough Hatch', 'Barkingside'], 'southwark': ['Denmark Hill', 'Dulwich', 'Surrey Quays', 'East Dulwich', 'Elephant and Castle', 'Newington', 'Nunhead', 'Peckham', 'Roth

In [37]:
dic ['Inner_london' ] = camden + southwark
dic ['Outer_london']  = brent + redbridge
dic.keys()

dict_keys(['brent', 'camden', 'redbridge', 'southwark', 'Inner_london', 'Outer_london'])

In [42]:
for a,b in dic.items():
    print(f'leanth of {a} is :{len(b)}')

leanth of brent is :19
leanth of camden is :22
leanth of redbridge is :18
leanth of southwark is :15
leanth of Inner_london is :37
leanth of Outer_london is :37


In [48]:
print(len(dic['Inner_london']))
print(len(dic['Outer_london']))

37
37


In [49]:
inner=(len(dic['Inner_london']))
outer=(len(dic['Outer_london']))
if inner>outer:
    print('you can start your tour from inner_london')
elif outer>inner:
    print('you can start your tour from outer_london')
else:
    print('both have same numbers of location you can choise as your wish')

both have same numbers of location you can choise as your wish


In [64]:
l=[brent,camden]
for i in l:
    if l.count(i)>1:
        print(i)

In [71]:
#Double each value in dictionary
dict1 = {'a': 1, 'b': 2, 'c': 3, 'd': 4, 'e': 5}
double_dict1 = {k:v*2 for (k,v) in dict1.items()}
print(double_dict1)

{'a': 2, 'b': 4, 'c': 6, 'd': 8, 'e': 10}


In [69]:
#update key in dictionary
keyupdate={k*2:y for k,y in dict1.items()}
keyupdate

{'aa': 1, 'bb': 2, 'cc': 3, 'dd': 4, 'ee': 5}

In [74]:
#creat dictionary
new={}
for i in range(10):
    new[i]=i*2
print(new)    

{0: 0, 1: 2, 2: 4, 3: 6, 4: 8, 5: 10, 6: 12, 7: 14, 8: 16, 9: 18}


In [78]:
# to the power 2 in dictionary
bb={}
ranga=range(10)
for i in ranga:
    if i%2==0:
        bb[i]=i**2
print(bb)        

{0: 0, 2: 4, 4: 16, 6: 36, 8: 64}


In [83]:
# Use dictionary comprehension
ba={}
fr={r:r**2 for r in range(10) if r%2==0}
fr


{0: 0, 2: 4, 4: 16, 6: 36, 8: 64}

In [89]:
# greater value in divtinary
greater={'a':1,'b':2,'c':3,'d':4,'e':5}
final={g:l for g,l in greater.items() if l>2}
final

{'c': 3, 'd': 4, 'e': 5}

In [90]:
greater={'a':1,'b':2,'c':3,'d':4,'e':5}
final={g:l for g,l in greater.items() if l>2 if l%2==0}
final

{'d': 4}

In [92]:
# fiind odd even in dictionary
even={d:('even' if v%2==0 else 'odd') for d,v in greater.items() }
even

{'a': 'odd', 'b': 'even', 'c': 'odd', 'd': 'even', 'e': 'odd'}

In [101]:
nested_dict = {'first':{'a':1}, 'second':{'b':2}}
float_dict = {outer_k: {float(inner_v) for (inner_k, inner_v) in outer_v.items()} for (outer_k, outer_v) in nested_dict.items()}
print(float_dict)

{'first': {1.0}, 'second': {2.0}}


In [1]:
nested_dict = {'first':{'a':1}, 'second':{'b':2}}

for (outer_k, outer_v) in nested_dict.items():
    for (inner_k, inner_v) in outer_v.items():
        outer_v.update({inner_k: float(inner_v)})
nested_dict.update({outer_k:outer_v})

print(nested_dict)

{'first': {'a': 1.0}, 'second': {'b': 2.0}}


In [14]:
pleasant_Sounding = ['Farm', 'Park', "Hill","Green"]

royal_Sounding = ['Royal','Queen','King']

In [7]:
dic.keys()

dict_keys(['brent', 'camden', 'redbridge', 'southwark'])

In [18]:
for b in dic['brent']:
    if any(i2 in b for i2 in pleasant_Sounding  ):
        print(b,'----pleasant_Sounding ')
    elif  any (i2 in b for i2 in royal_Sounding):
            print(b,'----royal_Sounding')
        
    

Brent Park ----pleasant_Sounding 
Dollis Hill ----pleasant_Sounding 
Kensal Green ----pleasant_Sounding 
Kingsbury ----royal_Sounding
Queen's Park ----pleasant_Sounding 
Wembley Park ----pleasant_Sounding 
Park Royal ----pleasant_Sounding 


In [21]:
for e in dic['camden']:
    if any(word in e for  word in pleasant_Sounding):
        print(e,'------pleasant_sound')
    elif any(word in e for word in royal_Sounding):
        print(e,'------royal_Sounding')
    

Chalk Farm ------pleasant_sound
Dartmouth Park ------pleasant_sound
Primrose Hill ------pleasant_sound
King's Cross ------royal_Sounding
Belsize Park ------pleasant_sound


In [26]:
def ram(location_list,word_list):
    return[a for a in location_list if any(word1 in a for word1 in word_list )]
print(ram(dic['camden'],pleasant_Sounding))

['Chalk Farm', 'Dartmouth Park', 'Primrose Hill', 'Belsize Park']


In [47]:

convert_to_string=str(brent)

def upper(location):
    return location.upper()
print(upper(convert_to_string))

['BRENT PARK', 'CHURCH END', 'DOLLIS HILL', 'HARLESDEN', 'KENSAL GREEN', 'KINGSBURY', 'NEASDEN', 'PRESTON', "QUEEN'S PARK", 'TOKYNGTON', 'WEMBLEY', 'WEMBLEY PARK', 'WILLESDEN', 'PARK ROYAL', 'KENTON', 'KILBURN', 'SUDBURY', 'BRONDESBURY', 'ALPERTON']


In [43]:
na='ritesh'
na.isupper()

False

In [45]:
name=('ritesh')
type(name)

str

In [39]:
import numpy as np
num=np.array([1,2,3,4,5,6])
type(num)

numpy.ndarray

In [42]:
joy=np.array([7,8,9,10,11,12])
type(joy)

numpy.ndarray

In [7]:
print(num[0])
print(num[4])
print(num[-1])
print(num[-3])
print(num[1:3])


1
5
6
4
[2 3]


In [10]:
joy.append(13)

AttributeError: 'numpy.ndarray' object has no attribute 'append'

In [11]:
joy

array([ 7,  8,  9, 10, 11, 12])

In [43]:
print(joy*2)
print(joy/4)
print(joy//6)
print(joy%2)
print(joy*num)
print(joy/num)
print(joy//num)
print(joy%num)
print(joy)
print(num)


[14 16 18 20 22 24]
[1.75 2.   2.25 2.5  2.75 3.  ]
[1 1 1 1 1 2]
[1 0 1 0 1 0]
[ 7 16 27 40 55 72]
[7.  4.  3.  2.5 2.2 2. ]
[7 4 3 2 2 2]
[0 0 0 2 1 0]
[ 7  8  9 10 11 12]
[1 2 3 4 5 6]


In [21]:
joy.remove(7)

AttributeError: 'numpy.ndarray' object has no attribute 'remove'

In [22]:
joy.pop(0)

AttributeError: 'numpy.ndarray' object has no attribute 'pop'

In [23]:
joy

array([ 7,  8,  9, 10, 11, 12])

In [25]:
joy.count(7)

AttributeError: 'numpy.ndarray' object has no attribute 'count'

In [30]:
del joy[0]


ValueError: cannot delete array elements

In [31]:
joy

array([ 7,  8,  9, 10, 11, 12])

In [33]:
#update value in array
joy[0]=2
joy

array([ 2,  8,  9, 10, 11, 12])

In [34]:
joy.extend(num)

AttributeError: 'numpy.ndarray' object has no attribute 'extend'

SyntaxError: invalid syntax (<ipython-input-36-7961fbe052cc>, line 1)

In [38]:
del joy
del

SyntaxError: invalid syntax (<ipython-input-38-341535a38a48>, line 2)