In [ ]:
dict_1 = {"Price": 3000}

In [2]:
price  = 3000

discount = int(inp("Please enter the discount")
print(price*100)/discount)

SyntaxError: invalid syntax (<ipython-input-2-46311b54ea00>, line 4)

In [20]:

def final_price(price,discount):
    return ((price * (100-discount)/100))

In [21]:
final_price(2000,25)

1500.0

In [22]:
final_price(10000,17)

8300.0

# Numpy

it is famous for it provides a new data structure thats optimized for calculation of arrays

## Numpy Arrays

Numpy arrays are tables of elements that all share the same data type(numeric)

In [1]:
# to call this library

import numpy as np

# data type : numpy.ndarray (ND - n-dimensional)

In [2]:
# creating arry of intergers

ar_int = np.array([0,1,2,3,4,5,6,7,8,9])

In [3]:
# type

type(ar_int)

numpy.ndarray

In [4]:
# length 

len(ar_int)

10

In [5]:
# checking for the hetrogenious creating

arr_hetro = np.array(['one',True,0,1,2,3,3.6])

In [6]:
arr_hetro

array(['one', 'True', '0', '1', '2', '3', '3.6'], dtype='<U4')

int,float,str,boolean

 1.Bool     2.int     3.float     4.Str

In [9]:
arr_hetro = np.array([0,1,2,3,3.6])
arr_hetro

array([0. , 1. , 2. , 3. , 3.6])

In [10]:
arr_hetro = np.array([0,1,2,3,3.6,True])
arr_hetro

array([0. , 1. , 2. , 3. , 3.6, 1. ])

In [11]:
arr_hetro = np.array([0,1,2,3,True])
arr_hetro

array([0, 1, 2, 3, 1])

In [12]:
# shape

arr_hetro.shape

(5,)

In [13]:
arr_hetro*2

array([0, 2, 4, 6, 2])

## Axis and dimensions:


1. You can think an axis means , its a direction in the coordinate plane.
2. Line ->1 Axis
3. Square -> 2 Axix
4. Cube -> 3 Axis



5. The number of elements in the tuple is the number of axis.
6. Elements value is length of the axis.

# Numpy testing operations

1. Positive indexing
2. Negitive indexing
3. +,-,*,/ (a) with another array. b) With scalar)
4. Adding /deleting/updating


## Missing data

In [14]:
# NAN (Not a number)
arr_hetro = np.array([True,0,1,2,np.nan,3.6])

In [15]:
arr_hetro

array([1. , 0. , 1. , 2. , nan, 3.6])

In [42]:
arr_hetro.dtype

dtype('float64')

In [53]:

if 'xyz'>'yvw':
    print("yes")
else:
    print("No")

No


In [54]:
type("X")

str

In [55]:
"joy"=="ritesh"

False

In [56]:
type("joy")==type("ritesh")

True

In [57]:
"joy">"ritesh"

False

In [58]:
'A'>'B'

False

In [59]:
'B'>'A'

True

In [60]:
"AB">"BA"

False

In [61]:
"Z"> "ABCDEF"

True

In [62]:
"a">"A"

True

In [63]:
ord("A")

65

In [64]:
# 1700 branches "id"

business_ids = np.array(range(1,1701))

In [65]:
business_ids.shape

(1700,)

In [67]:
# Access 10 ids from first and last

business_ids[:10]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [68]:
business_ids[-10:]

array([1691, 1692, 1693, 1694, 1695, 1696, 1697, 1698, 1699, 1700])

In [69]:
# creating one matrix by reshaping all this 1700 elements.


id_matrix = business_ids.reshape(170,10)

In [70]:
id_matrix.shape

(170, 10)

In [71]:
id_matrix

array([[   1,    2,    3, ...,    8,    9,   10],
       [  11,   12,   13, ...,   18,   19,   20],
       [  21,   22,   23, ...,   28,   29,   30],
       ...,
       [1671, 1672, 1673, ..., 1678, 1679, 1680],
       [1681, 1682, 1683, ..., 1688, 1689, 1690],
       [1691, 1692, 1693, ..., 1698, 1699, 1700]])

In [72]:
# column
id_matrix[:,0]

array([   1,   11,   21,   31,   41,   51,   61,   71,   81,   91,  101,
        111,  121,  131,  141,  151,  161,  171,  181,  191,  201,  211,
        221,  231,  241,  251,  261,  271,  281,  291,  301,  311,  321,
        331,  341,  351,  361,  371,  381,  391,  401,  411,  421,  431,
        441,  451,  461,  471,  481,  491,  501,  511,  521,  531,  541,
        551,  561,  571,  581,  591,  601,  611,  621,  631,  641,  651,
        661,  671,  681,  691,  701,  711,  721,  731,  741,  751,  761,
        771,  781,  791,  801,  811,  821,  831,  841,  851,  861,  871,
        881,  891,  901,  911,  921,  931,  941,  951,  961,  971,  981,
        991, 1001, 1011, 1021, 1031, 1041, 1051, 1061, 1071, 1081, 1091,
       1101, 1111, 1121, 1131, 1141, 1151, 1161, 1171, 1181, 1191, 1201,
       1211, 1221, 1231, 1241, 1251, 1261, 1271, 1281, 1291, 1301, 1311,
       1321, 1331, 1341, 1351, 1361, 1371, 1381, 1391, 1401, 1411, 1421,
       1431, 1441, 1451, 1461, 1471, 1481, 1491, 15

In [73]:
# Row
id_matrix[0,:]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [75]:
id_matrix[0:5]

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50]])

In [76]:
# access a specific part

id_matrix[:5,:5]

array([[ 1,  2,  3,  4,  5],
       [11, 12, 13, 14, 15],
       [21, 22, 23, 24, 25],
       [31, 32, 33, 34, 35],
       [41, 42, 43, 44, 45]])

In [77]:
id_matrix.shape

# 170 rows 
# 10 columns
# 2 dimensions(number of elements in the tuple)

(170, 10)

In [79]:
# minimum in each and every column

col_min = np.min(id_matrix, axis = 0)
col_min

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [80]:
# minimum in each and every column

col_max = np.max(id_matrix, axis = 0)
col_max

array([1691, 1692, 1693, 1694, 1695, 1696, 1697, 1698, 1699, 1700])

In [82]:
# minimum in each and every Row

row_min = np.min(id_matrix, axis = 1)
print(len(row_min))
row_min

170


array([   1,   11,   21,   31,   41,   51,   61,   71,   81,   91,  101,
        111,  121,  131,  141,  151,  161,  171,  181,  191,  201,  211,
        221,  231,  241,  251,  261,  271,  281,  291,  301,  311,  321,
        331,  341,  351,  361,  371,  381,  391,  401,  411,  421,  431,
        441,  451,  461,  471,  481,  491,  501,  511,  521,  531,  541,
        551,  561,  571,  581,  591,  601,  611,  621,  631,  641,  651,
        661,  671,  681,  691,  701,  711,  721,  731,  741,  751,  761,
        771,  781,  791,  801,  811,  821,  831,  841,  851,  861,  871,
        881,  891,  901,  911,  921,  931,  941,  951,  961,  971,  981,
        991, 1001, 1011, 1021, 1031, 1041, 1051, 1061, 1071, 1081, 1091,
       1101, 1111, 1121, 1131, 1141, 1151, 1161, 1171, 1181, 1191, 1201,
       1211, 1221, 1231, 1241, 1251, 1261, 1271, 1281, 1291, 1301, 1311,
       1321, 1331, 1341, 1351, 1361, 1371, 1381, 1391, 1401, 1411, 1421,
       1431, 1441, 1451, 1461, 1471, 1481, 1491, 15

In [84]:
# Maximum in each and every Row

row_max = np.max(id_matrix, axis = 1)
print(len(row_max))
row_max

170


array([  10,   20,   30,   40,   50,   60,   70,   80,   90,  100,  110,
        120,  130,  140,  150,  160,  170,  180,  190,  200,  210,  220,
        230,  240,  250,  260,  270,  280,  290,  300,  310,  320,  330,
        340,  350,  360,  370,  380,  390,  400,  410,  420,  430,  440,
        450,  460,  470,  480,  490,  500,  510,  520,  530,  540,  550,
        560,  570,  580,  590,  600,  610,  620,  630,  640,  650,  660,
        670,  680,  690,  700,  710,  720,  730,  740,  750,  760,  770,
        780,  790,  800,  810,  820,  830,  840,  850,  860,  870,  880,
        890,  900,  910,  920,  930,  940,  950,  960,  970,  980,  990,
       1000, 1010, 1020, 1030, 1040, 1050, 1060, 1070, 1080, 1090, 1100,
       1110, 1120, 1130, 1140, 1150, 1160, 1170, 1180, 1190, 1200, 1210,
       1220, 1230, 1240, 1250, 1260, 1270, 1280, 1290, 1300, 1310, 1320,
       1330, 1340, 1350, 1360, 1370, 1380, 1390, 1400, 1410, 1420, 1430,
       1440, 1450, 1460, 1470, 1480, 1490, 1500, 15

In [90]:
id_matrix.shape[1]

10

In [88]:
(1,2,3,4)[0]

1

In [1]:
# i want you to select 5 any numburs randomly from 10 columns 

for group in range(id_matrix.shape[1]):
    print("Group {}: {}".format(group+1,np.random.choice(id_matrix[:,group],replace = False)))

NameError: name 'id_matrix' is not defined

In [94]:
for var in range(id_matrix.shape[1]):
    print(var)

0
1
2
3
4
5
6
7
8
9


In [ ]:
np.random.choice

In [ ]:
np.random.choice()